import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: ['lh3.googleusercontent.com'],
  },
   typescript: {
    ignoreBuildErrors: true,
  }, 
  async redirects() {
    return [
        { source: "/biggest-tax-refund", destination: "/", permanent: false },
        { source: "/form-940", destination: "/", permanent: false },
        { source: "/form-941", destination: "/", permanent: false },
        { source: "/mw507", destination: "/", permanent: false },
        { source: "/w9-form", destination: "/", permanent: false },
        { source: "/fica-taxes", destination: "/", permanent: false },
        { source: "/author/victoriaward", destination: "/", permanent: false },
        { source: "/g4-form", destination: "/", permanent: false },
        { source: "/adoption-credit", destination: "/", permanent: false },
        { source: "/tax-levy", destination: "/", permanent: false },
        { source: "/irs-scams", destination: "/", permanent: false },
        { source: "/robinhood-taxes", destination: "/", permanent: false },
        { source: "/payroll-deductions", destination: "/", permanent: false },
        { source: "/contact-us3", destination: "/", permanent: false },
        { source: "/147c-letter", destination: "/", permanent: false },
        { source: "/schedule-appointment", destination: "/", permanent: false },
        { source: "/employment-taxes-pastors", destination: "/", permanent: false },
        { source: "/irs-form-1310", destination: "/", permanent: false },
        { source: "/irs-form-720", destination: "/", permanent: false },
        { source: "/irs-form-56", destination: "/", permanent: false },
        { source: "/irs-code-766", destination: "/", permanent: false },
        { source: "/irs-form-6166", destination: "/", permanent: false },
        { source: "/irs-form-8919", destination: "/", permanent: false },
        { source: "/irs-form-8821", destination: "/", permanent: false },
        { source: "/irs-form-843", destination: "/", permanent: false },
        { source: "/congratulations-from-giovanni", destination: "/", permanent: false },
        { source: "/irs-form-2555", destination: "/", permanent: false },
        { source: "/pre-tax-deduction", destination: "/", permanent: false },
        { source: "/taxes-on-stocks", destination: "/", permanent: false },
        { source: "/legal-order-lts", destination: "/", permanent: false },
        { source: "/audited-found-guilty", destination: "/", permanent: false },
        { source: "/irs-audit-attorney", destination: "/", permanent: false },
        { source: "/570-irs-code", destination: "/", permanent: false },
        { source: "/irs-form-5564", destination: "/", permanent: false },
        { source: "/irs-form-2210", destination: "/", permanent: false },
        { source: "/w2-vs-w4", destination: "/", permanent: false },
        { source: "/tax-relief-attorney", destination: "/", permanent: false },
        { source: "/846-irs-code", destination: "/", permanent: false },
        { source: "/irs-form-4852", destination: "/", permanent: false },
        { source: "/tax-lien-foreclosure", destination: "/", permanent: false },
        { source: "/irs-form-8802", destination: "/", permanent: false },
        { source: "/tax-collection-appeals", destination: "/", permanent: false },
        { source: "/irs-code-150", destination: "/", permanent: false },
        { source: "/tax-evasion-felony", destination: "/", permanent: false },
        { source: "/tax-abatement-explained", destination: "/", permanent: false },
        { source: "/irs-form-8949", destination: "/", permanent: false },
        { source: "/irs-1099-form", destination: "/", permanent: false },
        { source: "/legal-order-lts", destination: "/", permanent: false },
        { source: "/category/:path*", destination: "/", permanent: false },
        { source: "/faq/:path+", destination: "/", permanent: false },
        { source: "/report-someone-irs", destination: "/", permanent: false },
        { source: "/faq/how-much-will-the-irs-usually-settle-for", destination: "/", permanent: false },
        { source: "/how-the-corona-virus-can-impact-your-taxes", destination: "/", permanent: false },
        { source: "/tax-debt-relief-irs-forgiveness-program", destination: "/", permanent: false },
        { source: "/what-does-as-of-date-mean-transcript", destination: "/", permanent: false },
        { source: "/avoid-tax-penalties-irs-fresh-start-program", destination: "/", permanent: false },
        { source: "/american-opportunity-tax-credit-eases-tuition-strain", destination: "/", permanent: false },
        { source: "/code-570-and-971-tax-transcript", destination: "/", permanent: false },
        { source: "/what-are-cp501-and-cp502-notices", destination: "/", permanent: false },
        { source: "/inside-scoop-the-irs-cp523-letter", destination: "/", permanent: false },
        { source: "/owing-irs-affect-credit-score", destination: "/", permanent: false },
        { source: "/real-estate-taxes-same-property", destination: "/", permanent: false },
        { source: "/file-bankruptcy-taxes-owed-irs", destination: "/", permanent: false },
        { source: "/irs-accepted-return-not-approved", destination: "/", permanent: false },
        { source: "/tax-topic-152-explained", destination: "/", permanent: false },
        { source: "/irs-audit-process-timeline", destination: "/", permanent: false },
        { source: "/failure-to-file-penalty", destination: "/", permanent: false },
        { source: "/write-off-political-donations", destination: "/", permanent: false },
        { source: "/tax-breaks-for-homeowners", destination: "/", permanent: false },
        { source: "/federal-unemployment-tax-act-futa", destination: "/", permanent: false },
        { source: "/768-irs-code-explained", destination: "/", permanent: false },
        { source: "/irs-form-433-b", destination: "/", permanent: false },
        { source: "/irs-10-year-rule", destination: "/", permanent: false },
        { source: "/irs-form-433-h", destination: "/", permanent: false },
        { source: "/irs-form-3520-a", destination: "/", permanent: false },
        { source: "/paying-taxes-lawsuit-settlement", destination: "/", permanent: false },
        { source: "/irs-form-433-d", destination: "/", permanent: false },
        { source: "/irs-w4-form-explained", destination: "/", permanent: false },
      ];
  },
};

export default nextConfig;
